### ISSUE TITLE
Reading a Standard synchrone Phonecard ??? Who helps ..

### ISSUE THREAD

**Issue by javaro** [L1L1/cardpeek#69]
I want to READ the contents of a standard chip Phonecard from any country through this program ..
Is this possible ? 
I was told these are SYNCHRONE cards .. while GSM cards ar ASYNCHRONE ..
Is there any  .lua script available for these standard telephone cards ..
1000x thanks in advance ..
JAN VAN ROSSUM
BELGIUM

**Comment by apannetrat** [comment]
There is no script that currently reads those cards in cardpeek.
Cardpeek uses the PCSC API to read cards. While there is some support for reading synchronous cards with PCSC it's far from perfect. I'm not sure we will add this to cardpeek in the future.

**Comment by L1L1** [comment]
There is no script that currently reads those cards in cardpeek.
Cardpeek uses the PCSC API to read cards. While there is some support for reading synchronous cards with PCSC it's far from perfect. I'm not sure we will add this to cardpeek in the future.

**Comment by javaro** [comment]
thx anyway .. 
If someone else can help .. or can write something for me , I would be great to give some compensation..
It's for hobby purposes only , I would like to read the contents , get the contents in a 'variable' and so i can write a program in ASP to decode this contents as described in :  

http://www.epanorama.net/documents/smartcard/telecard.html

I am not electronically able to understand what is described here to read a card ..
The decode of this data I can do .. this is not the problem.
![img_1011](https://cloud.githubusercontent.com/assets/15218948/10638814/17a38a9e-780d-11e5-90b6-4ede845a407d.JPG)
![f256-demo-test-card-100-units-ext](https://cloud.githubusercontent.com/assets/15218948/10638822/26d4280c-780d-11e5-961c-02f5926bcfe0.jpg)
