### ISSUE TITLE
MOBIB parsing of new blocks & new type of card (anonymous)

### ISSUE THREAD

**Issue by michael79bxl** [L1L1/cardpeek#73]
Support for anonymous card:

Block
- Holder Extended (record id="1+2")

Blocks on my card:
- Contracts
- Counters
- Special events
- Contract list
- Free
- Public param.
- Miscellaneous
- Load Log
- Purchase Log

**Comment by L1L1** [comment]
I need to get my hands on one of those cards first... I'm not in Brussels, but I travel there from time to time.

**Comment by michael79bxl** [comment]
I can send a sample output if you need :D

**Comment by L1L1** [comment]
I finally flew to Brussels a few days ago and got one of the new cards, I will examine it and some additional sample output might be welcome :-)

**Comment by Reventl0v** [comment]
Hi. Any news on that ? I just got a mobib card and wanted to see if I could read some stuff, but it seems it's not supported right now (I get only « RECV 6A86 # Wrong parameter(s) P1-P2 - Incorrect parameters P1-P2 »).

Is this the same issue as in this thread ?

**Comment by michael79bxl** [comment]
Here is the result using Calypso parsing


[mobib.txt](https://github.com/L1L1/cardpeek/files/423774/mobib.txt)

**Comment by michael79bxl** [comment]
STIB/MIVB now allows to access the card online using the eID reader.

https://www.stib-mivb.be/mystib/
